### PR TITLE
Fix #111

### LINKED ISSUE #111: "allowUpscale" parameter shouldn't appear in Imgix URL
The `allowUpscale: false` parameter seems to work fine with Imgix (in that it limits the `w` parameter that is sent to Imgix to the width of the original image), however it gets added to the list of query string parameters in the Imgix URL, which still works (the image loads fine) but causes a weird issue with Facebook Open Graph. The reason is that weirdly, Facebook changes `?allowUpscale=&` to `?allowUpscale&` and even more weirdly, that makes Imgix return a 404.

### PR DESCRIPTION
**Pull request by benface**

### CODE REVIEW

**Comment by benface** [comment]
I realized that removing the `allowUpscale` parameter from the URL was not enough to fix my issue with Open Graph, because there was another empty parameter, the `q` parameter. I'm not sure why it was empty, but I know it wasn't needed in my case because I use `auto: 'compress,format'`. So I added a condition to not set `q` if `compress` is used, and no more empty parameters, which means Facebook properly reads my images now! :) And after thinking about it, it's probably not that weird that it didn't work; I use "secure URLs" on Imgix so I imagine the signature didn't match anymore if even one character in the URL changed.

**Comment by aelvan** [comment]
Fixes for these things have been rolled into v1.6.2. The fix you provided for removing `allowUpscale` was implemented to early. And that bug could happen to other properties too. So I'm both removing all overriable config settings, and removing any keys that have empty values, before creating the transform string to Imgix, just to be sure. 

Regarding `q`, it might be that you were using an image file with an extension that wasn't recognized by my code, .jpeg for instance. I've improved on this so that it will always fall back to the value of `jpegQuality` if the extension can't be determined. 

You're right that `q` may not be needed if using `auto: 'compress'`. But it can be, to override the quality setting, but still remove meta data and similar things. By default it will always be added by Imager to keep things in line with the defaults set in Imager. If you want to use the quality set by auto, you can pass `q: ''` to your transform and it will be deleted from the transform string.

**Comment by benface** [comment]
@aelvan Thank you, I just updated to v1.6.2. Based on what you're saying, it seems there should be a `q` parameter in the URL of the following transform:
```
craft.imager.transformImage(image, { width: 1200, ratio: 2, position: '50% 50%', allowUpscale: false, auto: 'compress,format' })
```
but there isn't. The only config options I set in imager.php are `imgixEnabled`, `imgixDomains`, `imgixUseHttps`, and `imgixSignKey`.

**Comment by aelvan** [comment]
Huh, yeah `q` should be in there. Weird. What type of image is it? And what's the generated url?

**Comment by benface** [comment]
It's a PNG, and the extension is all-caps. Here's the generated URL: https://benface.imgix.net/assets/amusebouches/kori.PNG?auto=compress%2Cformat&fit=max&ixlib=php-1.1.0&position=50%2050&q=80&w=2340&s=be6231cc13f5d5cf9425ed9419373d9a

**Comment by benface** [comment]
Whoops it is in there. Let me find the one I had before... unless I just didn't see it...

**Comment by benface** [comment]
OH. I bet the problem was due to old template caches... It definitely works now. Sorry!

**Comment by aelvan** [comment]
Pweeh, great! Was starting to doubt myself there. ;)

**Pull request closed without merging**
